name: etsp
channels:
  - pytorch
  - conda-forge
dependencies:
  - python>=3.10
  - pytorch
  - torchvision
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - pillow
  - tqdm
  - pip
  - libsndfile
  - librosa
  - pysoundfile
  - pip:
      - gdown
